In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
#txt path
txt_path = 'vdjdb-2023-06-01/vdjdb.txt'

#read txt file
df = pd.read_csv(txt_path, sep='\t')

#show the first 5 rows
df.head()

,complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,...,antigen.species,reference.id,method,meta,cdr3fix,vdjdb.score,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp
0,1,TRA,CIVRAPGRADMRF,TRAV26-1*01,TRAJ43*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,...,HIV-1,PMID:15596521,"{""frequency"": """", ""identification"": ""tetramer-...","{""cell.subset"": ""CD8+"", ""clone.id"": """", ""donor...","{""cdr3"": ""CIVRAPGRADMRF"", ""cdr3_old"": ""CIVRAPG...",2,sort,sanger,no,no
1,1,TRB,CASSYLPGQGDHYSNQPQHF,TRBV13*01,TRBJ1-5*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,...,HIV-1,PMID:15596521,"{""frequency"": """", ""identification"": ""tetramer-...","{""cell.subset"": ""CD8+"", ""clone.id"": """", ""donor...","{""cdr3"": ""CASSYLPGQGDHYSNQPQHF"", ""cdr3_old"": ""...",2,sort,sanger,no,no
2,0,TRB,CASSFEAGQGFFSNQPQHF,TRBV13*01,TRBJ1-5*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,...,HIV-1,PMID:15596521,"{""frequency"": """", ""identification"": ""tetramer-...","{""cell.subset"": ""CD8+"", ""clone.id"": """", ""donor...","{""cdr3"": ""CASSFEAGQGFFSNQPQHF"", ""cdr3_old"": ""C...",2,sort,sanger,no,no
3,2,TRA,CAVPSGAGSYQLTF,TRAV20*01,TRAJ28*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,...,HIV-1,PMID:15596521,"{""frequency"": """", ""identification"": ""tetramer-...","{""cell.subset"": ""CD8+"", ""clone.id"": """", ""donor...","{""cdr3"": ""CAVPSGAGSYQLTF"", ""cdr3_old"": ""CAVPSG...",2,sort,sanger,no,no
4,2,TRB,CASSFEPGQGFYSNQPQHF,TRBV13*01,TRBJ1-5*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,...,HIV-1,PMID:15596521,"{""frequency"": """", ""identification"": ""tetramer-...","{""cell.subset"": ""CD8+"", ""clone.id"": """", ""donor...","{""cdr3"": ""CASSFEPGQGFYSNQPQHF"", ""cdr3_old"": ""C...",2,sort,sanger,no,no

In [ ]:
#将txt文件转换为csv文件
df.to_csv('vdjdb.csv', index=False)

In [13]:
df = pd.read_csv('vdjdb.csv')

In [24]:
#print all of title
df.head()
print(df.columns)

Index(['complex.id', 'gene', 'cdr3', 'v.segm', 'j.segm', 'species', 'mhc.a',
       'mhc.b', 'mhc.class', 'antigen.epitope', 'antigen.gene',
       'antigen.species', 'reference.id', 'method', 'meta', 'cdr3fix',
       'vdjdb.score', 'web.method', 'web.method.seq', 'web.cdr3fix.nc',
       'web.cdr3fix.unmp'],
      dtype='object')

In [16]:
# Analyze the data for each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92771 entries, 0 to 92770
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   complex.id        92771 non-null  int64
 1   gene              92771 non-null  object
 2   cdr3              92771 non-null  object
 3   v.segm            92670 non-null  object
 4   j.segm            91626 non-null  object
 5   species           92771 non-null  object
 6   mhc.a             92771 non-null  object
 7   mhc.b             92771 non-null  object
 8   mhc.class         92771 non-null  object
 9   antigen.epitope   92771 non-null  object
 10  antigen.gene      92709 non-null  object
 11  antigen.species   92771 non-null  object
 12  reference.id      91260 non-null  object
 13  method            92771 non-null  object
 14  meta              92771 non-null  object
 15  cdr3fix           92771 non-null  object
 16  vdjdb.score       92771 non-null  int64
 17  web.method        92771 non-null  object
 18  web.method.seq    92771 non-null  object
 19  web.cdr3fix.nc    92771 non-null  object
 20  web.cdr3fix.unmp  92771 non-null  object
dtypes: int64(2), object(19)
memory usage: 14.9+ MB

In [20]:
df.describe(include='all')

,complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,...,antigen.species,reference.id,method,meta,cdr3fix,vdjdb.score,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp
count,92771.000000,92771,92771,92670,91626,92771,92771,92771,92771,92771,...,92771,91260,92771,92771,92771,92771.000000,92771,92771,92771,92771
unique,NaN,2,68994,224,71,3,119,45,2,1169,...,42,312,8567,4247,71912,NaN,3,4,2,2
top,NaN,TRB,CASSIRSSYEQYF,TRBV19*01,TRBJ2-7*01,HomoSapiens,HLA-A*03:01,B2M,MHCI,KLGGALQAK,...,CMV,https://www.10xgenomics.com/resources/applicat...,"{""frequency"": ""1/25584"", ""identification"": ""de...","{""cell.subset"": """", ""clone.id"": """", ""donor.MHC...","{""cdr3"": ""CASSIRSSYEQYF"", ""cdr3_old"": ""CASSIRS...",NaN,sort,singlecell,no,no
freq,NaN,54722,361,5978,9182,85329,29264,88368,88368,27948,...,38345,40716,20392,22446,323,NaN,89640,61602,92337,89847
mean,10089.612379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.196699,NaN,NaN,NaN,NaN
std,10197.643859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.567001,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
25%,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
50%,7402.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
75%,18998.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
max,30594.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN

In [ ]:
# Check for duplicate rows
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

In [ ]:
# Check for missing values in each column
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)

In [ ]:
#处理缺失值（以删除含有缺失值的行为例）
df = df.dropna()
# 或者，对于某些特定列使用填充策略，例如用列的均值或众数填充
# df['some_column'] = df['some_column'].fillna(value=df['some_column'].mean())

In [ ]:
#格式化数据（确保数据类型正确）
# df['some_date_column'] = pd.to_datetime(df['some_date_column'])
# df['some_numeric_column'] = pd.to_numeric(df['some_numeric_column'], errors='coerce')

In [ ]:
#标准化数据（例如，将所有文本列转换为小写）
# df['some_text_column'] = df['some_text_column'].str.lower()

In [ ]:
#异常值处理（示例：删除超出3倍标准差的数据）
# for col in ['some_numeric_column']:
#     upper_limit = df[col].mean() + 3*df[col].std()
#     lower_limit = df[col].mean() - 3*df[col].std()
#     df = df[(df[col] <= upper_limit) & (df[col] >= lower_limit)]

In [ ]:
#特征提取（示例：从字符串中提取特定信息作为新列）
# df['new_feature'] = df['some_column'].apply(lambda x: extract_info(x))
# 保存清洗后的数据
#df.to_csv('vdjdb_processed.csv', index=False)